name: CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up JDK
        uses: actions/setup-java@v2
        with:
          java-version: '17'

      - name: Build with Gradle
        run: ./gradlew build

      - name: Set up Docker
        uses: byloth/docker-setup-action@v1

      - name: Start Docker daemon
        run: |
          docker info
          sudo service docker start

      - name: Start Testcontainers
        run: docker pull testcontainers/ryuk:0.3.0

      - name: Run tests
        run: ./gradlew test